thank you. here are the new build logs
Finished Step #2 - "preparer"
Starting Step #3 - "pack"
Pulling image: gcr.io/k8s-skaffold/pack
Using default tag: latest
latest: Pulling from k8s-skaffold/pack
396c31837116: Pulling fs layer
9776b10d5c8c: Pulling fs layer
52cb9ac3197f: Pulling fs layer
9776b10d5c8c: Verifying Checksum
9776b10d5c8c: Download complete
396c31837116: Verifying Checksum
396c31837116: Download complete
52cb9ac3197f: Verifying Checksum
52cb9ac3197f: Download complete
396c31837116: Pull complete
9776b10d5c8c: Pull complete
52cb9ac3197f: Pull complete
Digest: sha256:221c0c0d9a90f46f108bb888a1da9e99c82ff631e8b1c63b0223ea951752bd53
Status: Downloaded newer image for gcr.io/k8s-skaffold/pack:latest
gcr.io/k8s-skaffold/pack:latest
296af0355d8a6dfeb9dd513820312430e29df281: Pulling from buildpacks/firebase-app-hosting-22/builder
Digest: sha256:b9f2101b272793a52d47e2175da58c9d939b4e10399912af06789e036e246acf
Status: Image is up to date for gcr.io/buildpacks/firebase-app-hosting-22/builder:296af0355d8a6dfeb9dd513820312430e29df281
latest: Pulling from buildpacks/firebase-app-hosting-22/run
e1a89dea01a6: Already exists
af059eb152dc: Pulling fs layer
66db767fbc86: Pulling fs layer
4972b34f89ae: Pulling fs layer
9871e18911f2: Pulling fs layer
9871e18911f2: Waiting
af059eb152dc: Verifying Checksum
af059eb152dc: Download complete
af059eb152dc: Pull complete
9871e18911f2: Download complete
66db767fbc86: Verifying Checksum
66db767fbc86: Download complete
4972b34f89ae: Verifying Checksum
4972b34f89ae: Download complete
66db767fbc86: Pull complete
4972b34f89ae: Pull complete
9871e18911f2: Pull complete
Digest: sha256:b89ca4ca12099fe76da6e0f6a30430f2b21557ee8ae07b61b9963143c4862dff
Status: Downloaded newer image for gcr.io/buildpacks/firebase-app-hosting-22/run:latest
===> ANALYZING
Image with name "us-central1-docker.pkg.dev/dodi-deals/firebaseapphosting-images/studio:a-qaj6lpmy5mwn" not found
===> DETECTING
target distro name/version labels not found, reading /etc/os-release file
4 of 5 buildpacks participating
google.nodejs.runtime        1.0.0
google.nodejs.firebasenextjs 0.0.1
google.nodejs.npm            1.1.0
google.nodejs.firebasebundle 0.0.1
===> RESTORING
===> BUILDING
target distro name/version labels not found, reading /etc/os-release file
=== Node.js - Runtime (google.nodejs.runtime@1.0.0) ===
2025/06/02 14:44:57 [DEBUG] GET https://dl.google.com/runtimes/ubuntu2204/nodejs/version.json
Adding image label google.runtime-version: nodejs20
2025/06/02 14:44:58 [DEBUG] GET https://dl.google.com/runtimes/ubuntu2204/nodejs/version.json
***** CACHE MISS: "nodejs"
Installing Node.js v20.19.2.
2025/06/02 14:44:58 [DEBUG] GET https://dl.google.com/runtimes/ubuntu2204/nodejs/nodejs-20.19.2.tar.gz
=== Node.js - Firebasenextjs (google.nodejs.firebasenextjs@0.0.1) ===
***** CACHE MISS: "npm_modules"
Installing nextjs adaptor 14.0.12
=== Node.js - Npm (google.nodejs.npm@1.1.0) ===
***** CACHE MISS: "npm_modules"
Installing application dependencies.
--------------------------------------------------------------------------------
Running "npm ci --quiet --no-fund --no-audit (NODE_ENV=development)"
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @types/handlebars@4.1.0: This is a stub types definition. handlebars provides its own type definitions, so you do not need this installed.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
added 799 packages in 37s
Done "npm ci --quiet --no-fund --no-audit (NODE_ENV=development)" (36.665290733s)
--------------------------------------------------------------------------------
Running "npm exec --prefix /layers/google.nodejs.firebasenextjs/npm_modules apphosting-adapter-nextjs-build"
Overriding Next Config to add configs optmized for Firebase App Hosting
Successfully created next.config.ts with Firebase App Hosting overrides
> nextn@0.1.0 build
> next build
   ▲ Next.js 15.2.3
   - Environments: .env.local
   Creating an optimized production build ...
 ✓ Compiled successfully
   Skipping validation of types
   Skipping linting
   Collecting page data ...
   Generating static pages (0/13) ...
   Generating static pages (3/13)
   Generating static pages (6/13)
 ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/profile". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout
    at a (/workspace/.next/server/chunks/384.js:3:86329)
    at d (/workspace/.next/server/chunks/384.js:26:101857)
    at j (/workspace/.next/server/app/profile/page.js:1:3980)
    at nL (/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:46773)
    at nF (/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:48548)
    at nq (/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:67434)
    at nH (/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:65009)
    at nU (/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:47125)
    at nF (/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:48594)
    at nF (/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:64360)
Error occurred prerendering page "/profile". Read more: https://nextjs.org/docs/messages/prerender-error
Export encountered an error on /profile/page: /profile, exiting the build.
 ⨯ Next.js build worker exited with code: 1 and signal: null
/layers/google.nodejs.firebasenextjs/npm_modules/node_modules/@apphosting/common/dist/index.js:36
                reject(new Error(`Build process exited with error code ${code}.`));
                       ^
Error: Build process exited with error code 1.
    at ChildProcess.<anonymous> (/layers/google.nodejs.firebasenextjs/npm_modules/node_modules/@apphosting/common/dist/index.js:36:24)
    at ChildProcess.emit (node:events:524:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
Node.js v20.19.2
Done "npm exec --prefix /layers/google.nodejs.firebasenextjs/npm_m..." (47.562130939s)
--------------------------------------------------------------------------------
failed to build: (error ID: 7021d348):
{"reason":"Failed Framework Build","code":"fah/failed-framework-build","userFacingMessage":"Your application failed to run the framework build command 'npm exec --prefix /layers/google.nodejs.firebasenextjs/npm_modules apphosting-adapter-nextjs-build' successfully. Please check the raw log to address the error and confirm that your application builds locally before redeploying.","rawLog":"(error ID: d0a693a9):
Overriding Next Config to add configs optmized for Firebase App Hosting
Successfully created next.config.ts with Firebase App Hosting overrides
> nextn@0.1.0 build
> next build
   ▲ Next.js 15.2.3
   - Environments: .env.local
   Creating an optimized production build ...
 ✓ Compiled successfully
   Skipping validation of types
   Skipping linting
   Collecting page data ...
   Generating static pages (0/13) ...
   Generating static pages (3/13)
   Generating static pages (6/13)
 ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/profile". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout
    at a (/workspace/.next/server/chunks/384.js:3:86329)
    at d (/workspace/.next/server/chunks/384.js:26:101857)
    at j (/workspace/.next/server/app/profile/page.js:1:3980)
    at nL (/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:46773)
    at nF (/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:48548)
    at nq (/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:67434)
    at nH (/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:65009)
    at nU (/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:47125)
    at nF (/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:48594)
    at nF (/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:64360)
Error occurred prerendering page "/profile". Read more: https://nextjs.org/docs/messages/prerender-error
Export encountered an error on /profile/page: /profile, exiting the build.
 ⨯ Next.js build worker exited with code: 1 and signal: null
/layers/google.nodejs.firebasenextjs/npm_modules/node_modules/@apphosting/common/dist/index.js:36
                reject(new Error(`Build process exited with error code ${code}.`));
                       ^
Error: Build process exited with error code 1.
    at ChildProcess.<anonymous> (/layers/google.nodejs.firebasenextjs/npm_modules/node_modules/@apphosting/common/dist/index.js:36:24)
    at ChildProcess.emit (node:events:524:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
Node.js v20.19.2"}
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51
Finished Step #3 - "pack"
ERROR
ERROR: build step 3 "gcr.io/k8s-skaffold/pack" failed: step exited with non-zero status: 1