ok the fix allowed me to move to the orders page as a manger. here is the error
Error: 9 FAILED_PRECONDITION: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/dodi-deals/firestore/indexes?create_composite=Cklwcm9qZWN0cy9kb2RpLWRlYWxzL2RhdGFiYXNlcy8oZGVmYXVsdCkvY29sbGVjdGlvbkdyb3Vwcy9vcmRlcnMvaW5kZXhlcy9fEAEaCgoGc3RhdHVzEAEaCwoHc3RvcmVJZBABGg0KCW9yZGVyRGF0ZRABGgwKCF9fbmFtZV9fEAE
    at getStoreOrdersByStatus (rsc://React/Server/file:///home/user/studio/.next/server/chunks/ssr/%5Broot%20of%20the%20server%5D__54c5abeb._.js?20:824:10)
    at resolveErrorDev (https://6000-firebase-studio-1748784407611.cluster-pb4ljhlmg5hqsxnzpc56r3prxw.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:17512:48)
    at processFullStringRow (https://6000-firebase-studio-1748784407611.cluster-pb4ljhlmg5hqsxnzpc56r3prxw.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:17728:23)
    at processFullBinaryRow (https://6000-firebase-studio-1748784407611.cluster-pb4ljhlmg5hqsxnzpc56r3prxw.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:17716:9)
    at progress (https://6000-firebase-studio-1748784407611.cluster-pb4ljhlmg5hqsxnzpc56r3prxw.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:17862:102)