i tried to publish the app but got an error
herer are the build logs

✓ Compiled successfully
   Skipping validation of types
   Skipping linting
   Collecting page data ...
   Generating static pages (0/13) ...
 ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/cart". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout
    at a (/workspace/.next/server/chunks/384.js:3:86329)
    at d (/workspace/.next/server/chunks/384.js:26:101857)
    at j (/workspace/.next/server/app/cart/page.js:1:1523)
    at nL (/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:46773)
    at nF (/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:48548)
    at nq (/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:67434)
    at nH (/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:65009)
    at nU (/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:47125)
    at nF (/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:48594)
    at nF (/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:64360)
Error occurred prerendering page "/cart". Read more: https://nextjs.org/docs/messages/prerender-error
Export encountered an error on /cart/page: /cart, exiting the build.
 ⨯ Next.js build worker exited with code: 1 and signal: null
/layers/google.nodejs.firebasenextjs/npm_modules/node_modules/@apphosting/common/dist/index.js:36
                reject(new Error(`Build process exited with error code ${code}.`));
                       ^
Error: Build process exited with error code 1.
    at ChildProcess.<anonymous> (/layers/google.nodejs.firebasenextjs/npm_modules/node_modules/@apphosting/common/dist/index.js:36:24)
    at ChildProcess.emit (node:events:524:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
Node.js v20.19.2"}
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51
Finished Step #3 - "pack"
ERROR
ERROR: build step 3 "gcr.io/k8s-skaffold/pack" failed: step exited with non-zero status: 1